### ISSUE TITLE
Only d435 

### ISSUE THREAD

**Issue by EduardoQD** [kevin-robb/eece5554-vslam#3]
Hello Kevin,

I would like to use the ORBSLAM3 but only with a D435 camera. How can I have to modify the script to subscribe at this topics?
Or if it necessary the SDK tool to launching the camera node in ROS?

**Comment by kevin-robb** [comment]
I already implemented it for the RealSense D435, just use the `realsense.yaml` and `realsense.sh`.  See the "Using Our Own Data" section at the bottom of the readme.

**Comment by kevin-robb** [comment]
To collect camera data in a rosbag you will need to connect the D435 to your computer and have the realsense ROS wrapper installed and running.

**Comment by EduardoQD** [comment]
Thanks Kevin, I've just gotten that the orbslam working.

Do you know something about knowing the x, y position in the map from the data of the data?
